### ISSUE TITLE
Week 7 Teacher Review

### ISSUE THREAD

**Issue by rpeddakama** [raad1masum/AP-CSA-Tri-1-Project#39]

**Comment by risaiwazaki** [comment]
READme & Scrumboard Review: 
Readme does not have anything from this week, no tickets of unit work shown. Tickets not up to date, no progress visible on individual tickets.

**Comment by jm1021** [comment]
You did an amazing job of discussing what you did.  I like that you made your review ticket as a part of the video script.   Very nice presentation.    Regarding Model and the Model definition, I like that you removed the multiple adds into a loop.  I was actually hoping that code would be placed in Model instead of remaining in control.   Something like regex on fron end for abstraction of path may have been better handled by capturing file and path distinctly in Model.   Regex requires logic ot be in frontend that should be in backend.  IMy score would be more like 7.5 as Model was not worked on enough.
